### ISSUE TITLE
week-4

### ISSUE THREAD

**Issue by alisamoua** [mad-java-ent-f20/indieProject#2]
Hi @pawaitemadisoncollege ,

I chose to do week 4 exercise with in the my project.  Screenshot is in my project screenshot folder.

Let me know if you would like me to change anything!

**Comment by pawaitemadisoncollege** [comment]
Looks great @alisamoua 

- [x] This method isn't needed as the getByProperty method covers this case in a more general way. https://github.com/mad-java-ent-f20/Init-to-Commit-Wedding-Planner/blob/c1925a568cf561c16b873e28e20632def7155e39/src/main/java/edu/matc/persistence/UserDao.java#L37-L56
- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/mad-java-ent-f20/Init-to-Commit-Wedding-Planner/blob/c1925a568cf561c16b873e28e20632def7155e39/src/test/java/edu/matc/persistence/UserDaoTest.java#L70
- [x] You'll likely notice, if you haven't already, that writing a Dao for each entity will be very repetitive - watch for the abstract/generic dao to be introduced in the coming week and plan to use it in your project so that you can use a single dao! Note that you will still have unit tests each for each entity(dao) to make sure that annotations and database relationships are set up correctly.
