### ISSUE TITLE
week 5

### ISSUE THREAD

**Issue by alisamoua** [mad-java-ent-f20/indieProject#3]
@pawaitemadisoncollege 
Forgot to create an issue to let you know week 5 is done (except for Generic Dao which I will be creating)

Let me know if you need me to change anything!

**Comment by pawaitemadisoncollege** [comment]
- [x] There's a out-of-place directory in your project called filepath that should be deleted. I think the cause is an undefined value in the log4j2: https://github.com/mad-java-ent-f20/Init-to-Commit-Wedding-Planner/blob/c33cc86dea09a2a795a11bddb02f0bcff9357128/src/main/resources/log4j2.properties#L21-L22.  Instead of filepath, this should be filename so this value is used instead: https://github.com/mad-java-ent-f20/Init-to-Commit-Wedding-Planner/blob/c33cc86dea09a2a795a11bddb02f0bcff9357128/src/main/resources/log4j2.properties#L3.  I think I have a bad example that you may have copied; now you know how to fix it! 
- [ ] It looks like you updated the UserDaoTest to include a test for the event, which is good! There should also be an EventDaoTest to fully test the EventDao and Event hibernate mappings.  Did I overlook this or ?? This EventDaoTest will stick around even after you convert to the GenericDao as it will verify that the mappings and relationships are always working.
